# Generated by Django 5.2 on 2025-06-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Contactform',
        ),
    ]
